name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup NodeJS
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Run Cypress tests
      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          build: npm run build   # only if you have a build step
          start: npm install       # start your app if needed
          wait-on: 'http://localhost:3000' # change port based on your app
          wait-on-timeout: 60
